### ISSUE TITLE
Homebridge crash

### ISSUE THREAD

**Issue by BEskandari** [fdegier/homebridge-jablotron-alarm#101]
**Describe The Problem:**

Upgrading to version v3.0.0-beta.11 and Homebridge crash in loop
**To Reproduce:**

Upgrade from version v3.0.0-beta.9 to version v3.0.0-beta.11
**Logs:**

```
TypeError: Cannot read properties of undefined (reading 'control-errors')
    at JablotronClient.containsErrorCode (/usr/local/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:17:29)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:95:35)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:514:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:535:22)
    at TLSSocket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
```
**Environment:**
* **Homebridge Version:** v1.7.0
* **Node Version:** v20.9.0
* **Homebridge-jablotron plugin version:** v3.0.0-beta.11
* **Operating System and OS Version:** Raspbian

**Comment by fdegier** [comment]
Did you update the config?

**Comment by BEskandari** [comment]
If you mean changing the segment ID to the SEC-XXXX yes I did. As said previously the beta 9 was working fine and as soon as I updated to beta 11 I have the issue.

**Comment by fdegier** [comment]
Can you beta12? And restart homebridge? I am also running the latest beta without issues.

**Comment by BEskandari** [comment]
Thanks beta 12 does not make Homebridge crash.
