### ISSUE TITLE
slow response / no response any more

### ISSUE THREAD

**Issue by tomdh76** [fdegier/homebridge-jablotron-alarm#113]
Lately I have an issue with this plugin in that controls from node red are not working reliably.

In the logs I see  these errors:

1) [homebridge-jablotron] This plugin slows down Homebridge. The read handler for the characteristic 'Security System Target State' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
2) [homebridge-jablotron] This plugin slows down Homebridge. The read handler for the characteristic 'Security System Current State' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
3)TypeError: Cannot read properties of undefined (reading 'service_type')
    at /var/lib/homebridge/node_modules/homebridge-jablotron/lib/jablotron.js:95:63
    at /var/lib/homebridge/node_modules/homebridge-jablotron/lib/jablotron.js:31:13
    at ClientRequest.<anonymous> (/var/lib/homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:106:17)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:519:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:709:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:551:22)
    at TLSSocket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)

Any suggestions?

**Comment by fdegier** [comment]
Can you elaborate what you mean with controls from node red?

Jablotron is not the best API, I see loads of network errors from their server, might be just that.

**Comment by tomdh76** [comment]
I use in node red 'homebridge control through node-red-contrib-homebridge-automation : hb-control. 
When I use things like set SecuritySystemTargetState it works sometimes but I also have  errors like: "AxiosError: timeout of 7000ms exceeded"
