### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading 'matchesErrorCode')

### ISSUE THREAD

**Issue by Faasteer** [fdegier/homebridge-jablotron-alarm#76]
Hi,
everything was fine recently, but now for the first time in a long time, i have a problem with this plugin that i can't handle. Every day, around 4:40 AM I get these error messages.

> [3/21/2022, 4:40:17 AM] [Jablotron] Error: TypeError: Cannot read properties of undefined (reading 'matchesErrorCode')
    at /homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:32:29
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:68:21)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[3/21/2022, 4:40:17 AM] [Jablotron] Unable to parse JSON data: {"http-code":200,"errors":[{"code":"METHOD.NOT-SUPPORTED","message":"Unknown method.","debug":"Unknown method."}]}

> [3/22/2022, 4:40:19 AM] [Jablotron] Error: TypeError: Cannot read properties of undefined (reading 'matchesErrorCode')
    at /homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:32:29
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:68:21)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[3/22/2022, 4:40:19 AM] [Jablotron] Unable to parse JSON data: {"http-code":200,"errors":[{"code":"METHOD.NOT-SUPPORTED","message":"Unknown method.","debug":"Unknown method."}]}

I run Docker on Synology 918+. Everything is the latest version available.
HomeBridge 4.42.0 (latest)
homebridge-jablotron v2.5.3
Node.js v16.14.0
Npm v8.3.1

Can you help me with that, please?

**Comment by Faasteer** [comment]
Hello,
first of all, I want to thank you for a quick reply. Unfortunately, now it's even worse than before the "repair". 😒 Now there are error messages in the log almost every minute. In fact, the same thing keeps happening.

Error 1:
> [3/26/2022, 11:52:25 AM] [Jablotron] Unable to parse JSON data: {"status":false,"error_status":"not_logged_in","checksum":"4e0a5f2250e13b14583a900483a182ab","server_id":"2685983-1648291945","client_id":null}

Error 2:
> [3/26/2022, 11:53:25 AM] [Jablotron] Error: TypeError: Cannot read properties of undefined (reading 'matchesErrorCode')
    at /homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:32:29
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:68:21)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Of course, now the jablotron in my homekit doesn't work and shows a few days old status. I checked the login, password and PIN, which I have specially created for this plugin, several times, but everything works (I log in on the website and in the application, the PIN on the keyboard is also OK).

So I tried the last "user thing" - return to version 2.5.3, immediately after installation the current status appeared and I can control the security of our house again.

**Comment by fdegier** [comment]
I finally logged some errors too:

```
[3/30/2022, 4:40:20 AM] [Jablotron] Error: Method not supported by Jablotron
    at /homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:33:31
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:68:21)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[3/30/2022, 4:40:20 AM] [Jablotron] Error: Method not supported by Jablotron
    at /homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:33:31
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:68:21)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[3/30/2022, 5:08:39 AM] [Homebridge UI] Starting terminal session
[3/30/2022, 5:09:25 AM] [Homebridge UI] Terminal session ended.
[3/30/2022, 6:05:01 AM] [Jablotron] Error: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:68:42)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[3/30/2022, 6:05:01 AM] [Jablotron] Unable to parse JSON data: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by fdegier** [comment]
Did you ever upgrade to the latest version?
